filebeat.prospectors:
- type: log
  paths:
    - /var/ossec/logs/alerts/alerts.json
  json.message_key: log
  json.keys_under_root: true
  json.overwrite_keys: true
#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["192.168.34.4:9200", "192.168.34.5:9200", "192.168.34.6:9200"]
  # Customized index name to wazuh-alerts-*
  index: "wazuh-alerts-4.x-%{+yyyy.MM.dd}"
setup.template.enabled: "false"
#setup.template.name: "wazuh3"
#setup.template.pattern: "wazuh3-*"